SET SERVEROUTPUT ON
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY*0.1 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=115);
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' employees got a raise.');
END;
/
DECLARE
    CURSOR C IS SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES ORDER BY HIRE_DATE;
    R C%ROWTYPE;
BEGIN
    for r in c loop
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||'-> '||r.first_name||' '||r.last_name||' was hired at '||r.hire_date); 
        exit when C%ROWCOUNT = 5;
    END LOOP;
END;
/
